---
title: "Upcoming Primary – August 13th"
author: "Kevin Konieczko"
date: "2024-07-29"
categories: [local politics]
description: Information about upcoming August primary
---

![Image credits: (2024). Voter-Guide-2024-Vote-On-Day \[Image\]. https://isthmus.com/news/news/2024-isthmus-august-primary-voter-guide/](VoterGuide.jpg){fig-align="center"}

The August primary will be held on August 13th. If you are a resident of the Badger Rock area, our polling locations for this election have been split up between Badger Rock Community Center (501 E Badger Rd, Madison, WI 53713) and the Highland Manor Storm Shelter (10 Manor Dr, Madison, WI 53713). If you are unsure which one you can check at the [Find My Polling Place](https://myvote.wi.gov/en-us/Find-My-Polling-Place) website.

![*\[Google Maps directions to Badger Rock Community Center\]. Retrieved August 10, 2024 from https://www.google.com/maps/place/Badger+Rock+Community+Center\]*](PollingLocation.JPG){fig-align="center"}

![\[Google Maps directions to Badger Rock Community Center\]. Retrieved August 10, 2024 from https://www.google.com/maps/place/Badger+Rock+Community+Center\]](PollingLocation.JPG){fig-align="center"}

This election will serve as a primary for the upcoming Senate race, Congressional race, and the Dane County Executive election later this year. There are also two proposed amendments to the state Constitution related to the administration of federal funds.

The Isthmus put together a great primer along with links to discussions of the various candidates and amendments along with information about registration and voting options: [Isthmus Voter Guide](https://isthmus.com/news/news/2024-isthmus-august-primary-voter-guide/)

If you are interested in helping at the polls, MyVoteWisconsin has a quick volunteer form located here: [Poll Worker Signup](https://myvote.wi.gov/en-us/Become-PollWorker)

See you at the polls!

###### 

###### 
