---
title: "Wisconsin Milkman Triathalon - JUNE 9, 2024"
date: "2024-03-01"
categories: [community]
description: Special Events Permit Notification
format:
  html:
    toc: true
---

### Dear Alders and Neighborhood Associations,

As part of the City of Madison Special Events Permit process, I am notifying you of the 3^rd^  Annual Wisconsin Milkman Triathlon happening on June 9, 2024. No roads will be fully closed down, however runners will be in a dedicated coned lane when running around the lake. The event starts at 7:00am at Olin Park, with a swim. They then jump on their bikes and head out of town towards Oregon. Once they return they will be running counter-clockwise around like Monona. You can expect to see runners from \~ 9:30am -- 4:00pm when the event ends. With the numbers we are expecting you shouldn't expect to see a mass group of runners, but more like 1-2 runners at a time, as they will be very spread out once they start on their run.

### The preliminary routes can be seen here:

Swim: see below

Bike: <https://www.mapmyrun.com/routes/view/5847006709>

Run: <https://www.mapmyrun.com/routes/view/5884777993>

ALL Maps - <https://wisconsinmilkman.com/wp-content/uploads/sites/46/2024/02/2024AllMilkmanMaps.pdf>

Note -- all city roads on the run route will include No Parking signs on the lake side of the street during the event (not both sides) and promptly removed as we come through to clean up. The City of Madison Police Department will be staged throughout the route where necessary to ensure the safety of the athletes, as well as to assist with getting local vehicles throughout the neighborhoods.

We look forward to producing another safe and fun event that is good for the community.  Please let me know if you have any questions or concerns.

Sincerely,

Abbey VanValkenburg\
Vice President\
2829 Royal Ave

Suite 100

Madison, WI  53713\
P: 608-316-5755

C: 616-460-8172
